name: Docker Build
on:
  pull_request:
    branches:
      - main

jobs:
  app:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      target: terraform-workshop-ecs-frontend
